### ISSUE TITLE
구글인증시 Error: redirect_uri_mismatch 에러발생 

### ISSUE THREAD

**Issue by kknd83** [young891221/Spring-Boot-Community-Web#10]
스프링부트 1.5 Oauth2 연동중  redirect_uri_mismatch 발생하네요. 이부분 원인이 무엇인지 궁금하네요.

**Comment by young891221** [comment]
구글 개발자 센터에 등록된 oauth2 인증 완료후 리다이렉트 되는 URI가 현재 서버에 세팅된 URI와 매칭되지 않아서 나는 메시지라 생각됩니다.

**Comment by kknd83** [comment]
답변 달아주신 내용을 제가 이해한게 맞다면 책을  327페이지를 보면 승인된 리다이렉션 URI를 http://localhost:8080/login/oauth2/client/google 라고 되었습니다. 현재 서버에 (스프링부트프로젝트)세팅된 URI 매칭되지않는다고 답변해주셨는데 그럼 해당 URI가 잘못된거 같은데요.? 이부분 수정이 필요한거같습니다. 
현제 테스트는 https 로컬적용후 테스트 하고있습니다.

**Comment by young891221** [comment]
음...어떻게 연동하신것인지 코드를 봐야 알겠지만 다시 테스트를 수행해 봤는데 저의 경우 잘 동작합니다.
1. master 브랜치(스프링 부트 2.0)
2. step1 브랜치(스프링 부트 1.5)
- 이 브랜치의 경우 application.yml에 clientId/clientSecret 정보를 입력해 주어야 동작합니다.

말씀주신 `redirect_uri_mismatch`는 제가 설정한 아이디로 테스트 한다면 `/google/complete`로 들어오도록 되어 있습니다.
본인이 설정한 계정을 사용하여 원하는 URI로 리다이렉트 하고 싶다면 앞서 말씀드린것처럼 구글 개발자 센터에서 리다이렉트 URI 설정에 'http://localhost:8080/login/oauth2/client/google '값을 추가하면 됩니다.
감사합니다.

**Comment by kknd83** [comment]
step1 브랜치로 프로젝트를 실습하는 내용을 캡쳐해서 young891221@gmail.com 보냈습니다. 확인 부탁드립니다.
감사합니다.

**Comment by kknd83** [comment]
승인된 리디렉션 URI 를 https://localhost:8443/login/google 변경했더니 잘 처리되었습니다. 
감사합니다.

**Comment by 0-ki** [comment]
저는 다른 케이스로, 공유기로 구성되어 있어서 localhost 가 아니라 127.0.0.1로 변경했더니 정상 작동 합니다.
